version: '3'
services:
  common:
    build:
      context: ./
      dockerfile: ./docker/common/Dockerfile
    image: grpcweb/common
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./:/code/grpc-demo/
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    ports:
      - "8080:8080"
#    links:
#      - server
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    depends_on:
      - common
    ports:
      - "8081:8081"
    volumes:
      - ./protos:/code/grpc-demo/protos
      - ./client/public:/code/grpc-demo/client/public
      - ./client/src/:/code/grpc-demo/client/src
      - ./client/package.json:/code/grpc-demo/client/package.json
      - ./client/vue.config.js:/code/grpc-demo/client/vue.config.js
      - ./client/babel.config.js:/code/grpc-demo/client/babel.config.js