version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: test
    volumes:
      - ./docker/db/empty:/var/lib/mysql/
      - ./docker/db/test.sql:/docker-entrypoint-initdb.d/dump.sql
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./WORKSPACE:/code/grpc-demo/WORKSPACE
      - ./protos:/code/grpc-demo/protos
      - ./server:/code/grpc-demo/server
    links:
      - db
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    ports:
      - "443:443"
    links:
      - server
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./client/public:/code/grpc-demo/client/public
      - ./client/src/:/code/grpc-demo/client/src
      - ./client/package.json:/code/grpc-demo/client/package.json
      - ./client/.eslintignore:/code/grpc-demo/client/.eslintignore
      - ./client/vue.config.js:/code/grpc-demo/client/vue.config.js
      - ./client/babel.config.js:/code/grpc-demo/client/babel.config.js
      - ./client/yarn.lock:/code/grpc-demo/client/yarn.lock